common:
    lid_topic:  "/hesai/pandar"  # for hiltislam2022 datasets
    imu_topic:  "/alphasense/imu"
    time_sync_en: false         # ONLY turn on when external time synchronization is really not possible
    time_offset_lidar_to_imu: 0.00176257  # lidar clock for lidar messages + time_offset_lidar_to_imu == imu clock for imu messages.

preprocess:
    lidar_type: 4                # 1 for Livox serials LiDAR, 2 for Velodyne LiDAR, 3 for ouster LiDAR, 
    scan_line: 32
    timestamp_unit: 0                 # 0-second, 1-milisecond, 2-microsecond, 3-nanosecond.
    blind: 2.0                          # the lidar is unable to measure distances less than blind.

mapping:
    acc_cov: 0.01                # \sigma^2*frequency
    gyr_cov: 4.0e-4
    b_acc_cov: 0.0036
    b_gyr_cov: 1.21e-6
    fov_degree:    180
    det_range:     120.0
    extrinsic_T: [0.00242799, -0.00417636, 0.0473645]
    extrinsic_R: [ 0.00297918168800893, -0.999995471835893,   -0.000425187228479353,
                   -0.999987625063738,  -0.00297746370788854, -0.00398552747493986,
                   0.00398424344827555,  0.000437055577284898,-0.999991967361022]
    gravity_m_s2: 9.81

publish:     
    scan_publish_en:  true       # 'false' will close all the point cloud output
    dense_publish_en: false       # false will low down the points number in a global-frame point clouds scan.
    scan_bodyframe_pub_en: true  # output the point cloud scans in a body frame
    publish_cloud_in_imu_frame: false # output the point cloud scans in IMU-frame or lidar-frame

pcd_save:
    pcd_save_en: false
    interval: -1                 # how many LiDAR frames saved in each pcd file; 
                                 # -1 : all frames will be saved in ONE pcd file.